const dummyConversations = [
  // Conversation 1: States of India
  {
    user: "696dd8cf06227e5f6a09c04e",
    title: "States of India",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 485,
      completion_tokens: 156,
      total_tokens: 641,
    },
    messages: [
      {
        role: "user",
        text: "How many states are in India?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-15T10:00:00Z",
      },
      {
        role: "assistant",
        text: "India has a total of 28 states and 8 union territories. The most recent change was in 2019 when Jammu & Kashmir was reorganized into two union territories.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-7dea8b27-1fd8-4286-866b-2421ed085474",
          prompt_tokens: 156,
          completion_tokens: 52,
          total_tokens: 208,
          finish_reason: "stop",
          latency_ms: 199,
        },
        createdAt: "2024-01-15T10:00:01Z",
      },
      {
        role: "user",
        text: "Which is the largest state by area?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-15T10:00:15Z",
      },
      {
        role: "assistant",
        text: "Rajasthan is the largest state in India by area, covering approximately 342,239 square kilometers. It accounts for about 10.4% of India's total geographical area. The state is known for its Thar Desert and rich cultural heritage.",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-8abc9c38-2ge9-5397-977c-3532fe196585",
          prompt_tokens: 178,
          completion_tokens: 58,
          total_tokens: 236,
          finish_reason: "stop",
          latency_ms: 215,
        },
        createdAt: "2024-01-15T10:00:16Z",
      },
      {
        role: "user",
        text: "And the smallest?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-15T10:00:30Z",
      },
      {
        role: "assistant",
        text: "Goa is the smallest state in India by area, covering just 3,702 square kilometers. Despite its small size, it's one of the most popular tourist destinations known for its beaches, churches, and Portuguese heritage.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-9bcd0d49-3hf0-6408-088d-4643gf207696",
          prompt_tokens: 151,
          completion_tokens: 46,
          total_tokens: 197,
          finish_reason: "stop",
          latency_ms: 178,
        },
        createdAt: "2024-01-15T10:00:31Z",
      },
    ],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:31Z",
  },

  // Conversation 2: JavaScript Help
  {
    user: "696dd8cf06227e5f6a09c04e",
    title: "JavaScript Array Methods",
    isPinned: true,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 612,
      completion_tokens: 289,
      total_tokens: 901,
    },
    messages: [
      {
        role: "user",
        text: "What is the difference between map and forEach in JavaScript?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-16T14:30:00Z",
      },
      {
        role: "assistant",
        text: "The key differences are:\n\n1. **Return Value**: `map()` returns a new array with transformed elements, while `forEach()` returns undefined.\n\n2. **Chaining**: `map()` can be chained with other array methods, `forEach()` cannot.\n\n3. **Use Case**: Use `map()` when you need to transform data, use `forEach()` for side effects like logging.\n\nExample:\n```javascript\nconst nums = [1, 2, 3];\nconst doubled = nums.map(n => n * 2); // [2, 4, 6]\nnums.forEach(n => console.log(n)); // undefined\n```",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-1abc1a11-1aa1-1111-111a-1111aa111111",
          prompt_tokens: 189,
          completion_tokens: 142,
          total_tokens: 331,
          finish_reason: "stop",
          latency_ms: 342,
        },
        createdAt: "2024-01-16T14:30:02Z",
      },
      {
        role: "user",
        text: "What about filter and reduce?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-16T14:31:00Z",
      },
      {
        role: "assistant",
        text: "**filter()**: Creates a new array with elements that pass a test condition.\n\n```javascript\nconst nums = [1, 2, 3, 4, 5];\nconst evens = nums.filter(n => n % 2 === 0); // [2, 4]\n```\n\n**reduce()**: Reduces an array to a single value by applying a function.\n\n```javascript\nconst nums = [1, 2, 3, 4];\nconst sum = nums.reduce((acc, n) => acc + n, 0); // 10\n```\n\n`reduce()` is the most powerful as it can implement map, filter, and more!",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-2bcd2b22-2bb2-2222-222b-2222bb222222",
          prompt_tokens: 215,
          completion_tokens: 147,
          total_tokens: 362,
          finish_reason: "stop",
          latency_ms: 356,
        },
        createdAt: "2024-01-16T14:31:02Z",
      },
      {
        role: "user",
        text: "Can you show reduce implementing map?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-16T14:32:00Z",
      },
      {
        role: "assistant",
        text: "Sure! Here's how to implement `map()` using `reduce()`:\n\n```javascript\nconst nums = [1, 2, 3];\n\n// Using map\nconst doubled1 = nums.map(n => n * 2);\n\n// Using reduce to do the same\nconst doubled2 = nums.reduce((acc, n) => {\n  acc.push(n * 2);\n  return acc;\n}, []);\n\nconsole.log(doubled1); // [2, 4, 6]\nconsole.log(doubled2); // [2, 4, 6]\n```\n\nThe accumulator starts as an empty array `[]`, and we push transformed values into it.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-3cde3c33-3cc3-3333-333c-3333cc333333",
          prompt_tokens: 208,
          completion_tokens: 0,
          total_tokens: 208,
          finish_reason: "stop",
          latency_ms: 289,
        },
        createdAt: "2024-01-16T14:32:02Z",
      },
    ],
    createdAt: "2024-01-16T14:30:00Z",
    updatedAt: "2024-01-16T14:32:02Z",
  },

  // Conversation 3: Cooking Recipe
  {
    user: "696dd8cf06227e5f6a09c04e",
    title: "Chicken Biryani Recipe",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 534,
      completion_tokens: 312,
      total_tokens: 846,
    },
    messages: [
      {
        role: "user",
        text: "How do I make chicken biryani at home?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-17T18:00:00Z",
      },
      {
        role: "assistant",
        text: "Here's a simplified Chicken Biryani recipe:\n\n**Ingredients:**\n- 500g chicken\n- 2 cups basmati rice\n- 2 onions (sliced)\n- 1 cup yogurt\n- Biryani masala, ginger-garlic paste\n- Saffron soaked in milk\n\n**Steps:**\n1. Marinate chicken with yogurt, spices for 1 hour\n2. Parboil rice with whole spices (70% cooked)\n3. Fry onions until golden brown\n4. Layer: chicken → rice → fried onions → saffron milk\n5. Dum cook on low heat for 25 minutes\n\nServe with raita!",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-4def4d44-4dd4-4444-444d-4444dd444444",
          prompt_tokens: 167,
          completion_tokens: 156,
          total_tokens: 323,
          finish_reason: "stop",
          latency_ms: 378,
        },
        createdAt: "2024-01-17T18:00:03Z",
      },
      {
        role: "user",
        text: "What is dum cooking?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-17T18:01:00Z",
      },
      {
        role: "assistant",
        text: "**Dum cooking** is a slow-cooking technique where food is cooked in its own steam.\n\n**How it works:**\n1. The pot is sealed with dough or a tight lid\n2. Cooked on very low heat (or coal on top and bottom)\n3. Steam trapped inside cooks the food evenly\n4. Flavors get infused into every layer\n\n**For biryani:** After layering, seal the pot with aluminum foil, then cover with lid. Cook on low flame for 20-25 minutes. Don't open the lid during cooking!\n\nThis is what gives biryani its signature aroma and perfectly cooked rice.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-5efg5e55-5ee5-5555-555e-5555ee555555",
          prompt_tokens: 183,
          completion_tokens: 98,
          total_tokens: 281,
          finish_reason: "stop",
          latency_ms: 267,
        },
        createdAt: "2024-01-17T18:01:02Z",
      },
      {
        role: "user",
        text: "Can I use regular rice instead of basmati?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-17T18:02:00Z",
      },
      {
        role: "assistant",
        text: "You can, but it won't be the same. Here's why basmati is preferred:\n\n**Basmati Rice:**\n- Long, separate grains after cooking\n- Aromatic fragrance\n- Doesn't become mushy\n- Absorbs flavors well\n\n**Regular Rice:**\n- Tends to stick together\n- No distinct aroma\n- Can become gluey in layered dishes\n\n**If you must substitute:** Use any long-grain rice like Jasmine. Avoid short-grain or sushi rice completely. Also, reduce water slightly as regular rice needs less water than basmati.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-6fgh6f66-6ff6-6666-666f-6666ff666666",
          prompt_tokens: 184,
          completion_tokens: 58,
          total_tokens: 242,
          finish_reason: "stop",
          latency_ms: 234,
        },
        createdAt: "2024-01-17T18:02:02Z",
      },
    ],
    createdAt: "2024-01-17T18:00:00Z",
    updatedAt: "2024-01-17T18:02:02Z",
  },

  // Conversation 4: Fitness Advice
  {
   
    user: "696dd8cf06227e5f6a09c04e",
    title: "Beginner Workout Plan",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 489,
      completion_tokens: 267,
      total_tokens: 756,
    },
    messages: [
      {
        role: "user",
        text: "I want to start working out but I have no experience. Where do I begin?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-18T06:30:00Z",
      },
      {
        role: "assistant",
        text: "Great decision! Here's a beginner-friendly approach:\n\n**Week 1-2: Build Habit**\n- Start with just 15-20 minutes\n- Focus on consistency, not intensity\n\n**Simple Starter Routine:**\n1. Warm-up: 5 min walk/jog in place\n2. Bodyweight squats: 10 reps\n3. Push-ups (knee push-ups ok): 8 reps\n4. Lunges: 8 each leg\n5. Plank: 20 seconds\n6. Cool down: stretching\n\n**Tips:**\n- Rest 1 minute between exercises\n- Do this 3 times per week\n- Don't skip rest days\n\nWould you like a specific schedule?",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-7ghi7g77-7gg7-7777-777g-7777gg777777",
          prompt_tokens: 156,
          completion_tokens: 145,
          total_tokens: 301,
          finish_reason: "stop",
          latency_ms: 356,
        },
        createdAt: "2024-01-18T06:30:02Z",
      },
      {
        role: "user",
        text: "Yes please! Also how important is diet?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-18T06:31:00Z",
      },
      {
        role: "assistant",
        text: '**Weekly Schedule:**\n- Monday: Workout\n- Tuesday: Rest or light walk\n- Wednesday: Workout\n- Thursday: Rest\n- Friday: Workout\n- Weekend: Active rest (swimming, cycling)\n\n**Diet is EXTREMELY important!** Often said: "Abs are made in the kitchen."\n\n**Basic Nutrition Rules:**\n1. **Protein**: 1.6-2g per kg bodyweight (chicken, eggs, dal, paneer)\n2. **Water**: 3-4 liters daily\n3. **Avoid**: Processed foods, excess sugar\n4. **Eat**: Whole foods, vegetables, fruits\n\n**Simple formula:**\n- Weight loss: Calories in < Calories out\n- Muscle gain: Calories in > Calories out + protein\n\nDiet contributes 70% to your results!',
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-8hij8h88-8hh8-8888-888h-8888hh888888",
          prompt_tokens: 178,
          completion_tokens: 122,
          total_tokens: 300,
          finish_reason: "stop",
          latency_ms: 312,
        },
        createdAt: "2024-01-18T06:31:03Z",
      },
      {
        role: "user",
        text: "How long until I see results?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-18T06:32:00Z",
      },
      {
        role: "assistant",
        text: "Here's a realistic timeline:\n\n**Week 1-2:**\n- You'll *feel* better (more energy, better sleep)\n- No visible changes yet\n\n**Week 3-4:**\n- *You* start noticing small changes\n- Clothes fit slightly better\n- Strength increases\n\n**Week 8-12:**\n- *Others* start noticing changes\n- Visible muscle definition\n- Significant strength gains\n\n**6+ months:**\n- Major transformation\n- New habits are automatic\n\n**Key reminder:** Progress isn't linear. Some weeks you'll feel stuck. Trust the process and stay consistent. Take progress photos monthly—the mirror lies, photos don't!",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-9ijk9i99-9ii9-9999-999i-9999ii999999",
          prompt_tokens: 155,
          completion_tokens: 0,
          total_tokens: 155,
          finish_reason: "stop",
          latency_ms: 278,
        },
        createdAt: "2024-01-18T06:32:02Z",
      },
    ],
    createdAt: "2024-01-18T06:30:00Z",
    updatedAt: "2024-01-18T06:32:02Z",
  },

  // Conversation 5: Travel Recommendations
  {
    
    user: "696dd8cf06227e5f6a09c04e",
    title: "Ladakh Trip Planning",
    isPinned: true,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 523,
      completion_tokens: 234,
      total_tokens: 757,
    },
    messages: [
      {
        role: "user",
        text: "I'm planning a trip to Ladakh next month. What should I know?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-19T20:00:00Z",
      },
      {
        role: "assistant",
        text: "Exciting! Ladakh is incredible. Here's what you need to know:\n\n**Best Time:** June to September (roads are open, weather is pleasant)\n\n**Essential Preparations:**\n1. **Acclimatization**: Spend 2 days in Leh before trekking/exploring\n2. **Permits**: Inner Line Permit required for Nubra, Pangong, etc.\n3. **Health**: Carry Diamox for altitude sickness\n4. **Cash**: ATMs are scarce; carry enough cash\n\n**Must-Visit Places:**\n- Pangong Lake\n- Nubra Valley\n- Khardung La Pass\n- Magnetic Hill\n- Monasteries: Thiksey, Hemis\n\nWhich month exactly are you planning?",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-0jkl0j00-0jj0-0000-000j-0000jj000000",
          prompt_tokens: 165,
          completion_tokens: 89,
          total_tokens: 254,
          finish_reason: "stop",
          latency_ms: 267,
        },
        createdAt: "2024-01-19T20:00:02Z",
      },
      {
        role: "user",
        text: "July. How many days do I need?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-19T20:01:00Z",
      },
      {
        role: "assistant",
        text: "July is perfect! Here's an ideal itinerary:\n\n**Minimum: 7 Days** | **Ideal: 10-12 Days**\n\n**7-Day Itinerary:**\n- Day 1-2: Arrive Leh, acclimatize, local sightseeing\n- Day 3: Leh → Nubra Valley (Khardung La)\n- Day 4: Nubra exploration, sand dunes, camel ride\n- Day 5: Nubra → Pangong Lake\n- Day 6: Pangong → Leh\n- Day 7: Buffer day / departure\n\n**Pro tip for July:**\n- Book accommodations in advance (peak season)\n- Carry rain gear (occasional showers)\n- Start early to avoid tourist crowds\n\nAre you planning a bike trip or by car?",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-1klm1k11-1kk1-1111-111k-1111kk111111",
          prompt_tokens: 178,
          completion_tokens: 78,
          total_tokens: 256,
          finish_reason: "stop",
          latency_ms: 234,
        },
        createdAt: "2024-01-19T20:01:02Z",
      },
      {
        role: "user",
        text: "By car. What about budget?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-19T20:02:00Z",
      },
      {
        role: "assistant",
        text: "Good choice! Here's a budget breakdown for 7 days:\n\n**Budget Trip (per person):**\n- Flights: ₹8,000-12,000 (book early)\n- Accommodation: ₹1,500/night × 6 = ₹9,000\n- Car rental with driver: ₹3,500/day × 5 = ₹17,500\n- Food: ₹800/day × 7 = ₹5,600\n- Permits: ₹500\n- Miscellaneous: ₹3,000\n\n**Total: ₹40,000-45,000 per person**\n\n**Mid-Range: ₹55,000-65,000**\n**Luxury: ₹80,000+**\n\n**Money-saving tips:**\n- Share car costs with other travelers\n- Eat at local dhabas\n- Book flights 2 months ahead\n\nWant me to suggest some reliable car rental contacts?",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-2lmn2l22-2ll2-2222-222l-2222ll222222",
          prompt_tokens: 180,
          completion_tokens: 67,
          total_tokens: 247,
          finish_reason: "stop",
          latency_ms: 256,
        },
        createdAt: "2024-01-19T20:02:02Z",
      },
    ],
    createdAt: "2024-01-19T20:00:00Z",
    updatedAt: "2024-01-19T20:02:02Z",
  },

  // Conversation 6: Movie Recommendations
  {
   
    user: "696dd8cf06227e5f6a09c04e",
    title: "Sci-Fi Movie Suggestions",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 467,
      completion_tokens: 198,
      total_tokens: 665,
    },
    messages: [
      {
        role: "user",
        text: "Suggest some mind-bending sci-fi movies like Inception",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-20T22:00:00Z",
      },
      {
        role: "assistant",
        text: "If you loved Inception, you'll enjoy these:\n\n**Same Director (Christopher Nolan):**\n1. **Interstellar** (2014) - Space, time dilation, emotional\n2. **Tenet** (2020) - Time inversion, very complex\n3. **The Prestige** (2006) - Not sci-fi but same twist style\n\n**Similar Mind-Benders:**\n4. **Arrival** (2016) - Linguistics meets time\n5. **Coherence** (2013) - Low budget, big concept\n6. **Predestination** (2014) - Time travel paradox\n7. **Primer** (2004) - Most complex time travel ever\n8. **Dark City** (1998) - Reality manipulation\n\nWhich interests you most?",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-3mno3m33-3mm3-3333-333m-3333mm333333",
          prompt_tokens: 145,
          completion_tokens: 98,
          total_tokens: 243,
          finish_reason: "stop",
          latency_ms: 234,
        },
        createdAt: "2024-01-20T22:00:02Z",
      },
      {
        role: "user",
        text: "Tell me more about Primer. Why is it complex?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-20T22:01:00Z",
      },
      {
        role: "assistant",
        text: "**Primer (2004)** is legendary for its complexity:\n\n**The Story:**\nTwo engineers accidentally build a time machine in their garage. They use it for stock market gains, but things spiral out of control.\n\n**Why it's complex:**\n1. Made on just $7,000 budget\n2. No exposition—characters talk like real engineers\n3. Multiple overlapping timelines\n4. Characters create copies of themselves\n5. By the end, there are 9+ timeline branches\n\n**Fun fact:** There are YouTube videos with 20+ minute explanations, and people still debate the ending.\n\n**My advice:** Watch it twice. First time for the experience, second time with a timeline chart open!\n\nRating: IMDb 6.9 (but cult classic status)",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-4nop4n44-4nn4-4444-444n-4444nn444444",
          prompt_tokens: 167,
          completion_tokens: 56,
          total_tokens: 223,
          finish_reason: "stop",
          latency_ms: 212,
        },
        createdAt: "2024-01-20T22:01:02Z",
      },
      {
        role: "user",
        text: "Any good sci-fi series instead of movies?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-20T22:02:00Z",
      },
      {
        role: "assistant",
        text: "Absolutely! Here are top sci-fi series:\n\n**Cerebral/Mind-bending:**\n1. **Dark** (Netflix) - German, time travel, masterpiece\n2. **Severance** (Apple TV) - Work-life split literally\n3. **Westworld** (HBO) - S1-2 are incredible\n\n**Space/Epic:**\n4. **The Expanse** - Best space politics ever\n5. **For All Mankind** - Alternate space race history\n\n**Quick Watch:**\n6. **Black Mirror** - Anthology, tech horror\n7. **Love, Death & Robots** - Animated shorts\n\n**My #1 recommendation:** Start with **Dark**. It's the TV equivalent of Inception/Primer. 3 perfect seasons with a planned ending.",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-5opq5o55-5oo5-5555-555o-5555oo555555",
          prompt_tokens: 155,
          completion_tokens: 44,
          total_tokens: 199,
          finish_reason: "stop",
          latency_ms: 189,
        },
        createdAt: "2024-01-20T22:02:02Z",
      },
    ],
    createdAt: "2024-01-20T22:00:00Z",
    updatedAt: "2024-01-20T22:02:02Z",
  },

  // Conversation 7: Learning Guitar
  {
    
    user: "696dd8cf06227e5f6a09c04e",
    title: "Guitar for Beginners",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 445,
      completion_tokens: 213,
      total_tokens: 658,
    },
    messages: [
      {
        role: "user",
        text: "I just bought my first guitar. How do I start learning?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-21T16:00:00Z",
      },
      {
        role: "assistant",
        text: 'Congratulations! Here\'s your beginner roadmap:\n\n**Week 1-2: Fundamentals**\n1. Learn to hold the guitar properly\n2. Memorize string names: E-A-D-G-B-E (Eddie Ate Dynamite Good Bye Eddie)\n3. Practice pressing strings without playing\n\n**Week 3-4: First Chords**\n- Start with: Em, Am, C, G, D\n- These 5 chords let you play hundreds of songs!\n\n**Week 5+: Simple Songs**\n- "Wonderwall" - Oasis\n- "Let It Be" - Beatles\n- "Perfect" - Ed Sheeran\n\n**Daily Practice:**\n- 15-30 minutes minimum\n- Finger tips will hurt initially (calluses form in 2-3 weeks)\n\nAcoustic or electric guitar?',
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-6pqr6p66-6pp6-6666-666p-6666pp666666",
          prompt_tokens: 148,
          completion_tokens: 112,
          total_tokens: 260,
          finish_reason: "stop",
          latency_ms: 289,
        },
        createdAt: "2024-01-21T16:00:02Z",
      },
      {
        role: "user",
        text: "Acoustic. My fingers hurt a lot, is that normal?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-21T16:01:00Z",
      },
      {
        role: "assistant",
        text: "Yes, completely normal! Here's what's happening:\n\n**The Pain Phase:**\n- Lasts 2-4 weeks for most beginners\n- Your fingertips are developing calluses\n- Acoustic steel strings hurt more than nylon/electric\n\n**Tips to Manage:**\n1. Practice 15-20 mins, take breaks\n2. Don't practice until fingers bleed\n3. Ice your fingertips after practice\n4. Press just hard enough for clear sound\n\n**Speed Up Callus Formation:**\n- Apply rubbing alcohol to fingertips after practice\n- Practice consistently (daily short sessions > occasional long ones)\n\n**Good News:** After 3-4 weeks, you won't feel pain anymore. The calluses become permanent even if you stop for months!",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-7qrs7q77-7qq7-7777-777q-7777qq777777",
          prompt_tokens: 152,
          completion_tokens: 56,
          total_tokens: 208,
          finish_reason: "stop",
          latency_ms: 212,
        },
        createdAt: "2024-01-21T16:01:02Z",
      },
      {
        role: "user",
        text: "What apps or YouTube channels do you recommend?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-21T16:02:00Z",
      },
      {
        role: "assistant",
        text: "Here are the best free resources:\n\n**YouTube Channels:**\n1. **JustinGuitar** - Best structured free course\n2. **Marty Music** - Easy song tutorials\n3. **Paul Davids** - Intermediate techniques\n\n**Apps:**\n1. **Yousician** - Interactive lessons (free tier available)\n2. **Ultimate Guitar** - Chord charts & tabs for any song\n3. **GuitarTuna** - Free tuner app (essential!)\n4. **Chordify** - Shows chords for any song\n\n**My Recommendation:**\nFollow JustinGuitar's beginner course in order. It's like having a free professional teacher. He's taught millions worldwide.\n\nStart here: justinguitar.com/categories/beginner-guitar-lessons",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-8rst8r88-8rr8-8888-888r-8888rr888888",
          prompt_tokens: 145,
          completion_tokens: 45,
          total_tokens: 190,
          finish_reason: "stop",
          latency_ms: 178,
        },
        createdAt: "2024-01-21T16:02:02Z",
      },
    ],
    createdAt: "2024-01-21T16:00:00Z",
    updatedAt: "2024-01-21T16:02:02Z",
  },

  // Conversation 8: Stock Market Basics
  {
   
    user: "696dd8cf06227e5f6a09c04e",
    title: "Stock Market Investing",
    isPinned: true,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 512,
      completion_tokens: 278,
      total_tokens: 790,
    },
    messages: [
      {
        role: "user",
        text: "I want to start investing in stocks. I'm a complete beginner with ₹10,000 to start.",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-22T10:00:00Z",
      },
      {
        role: "assistant",
        text: "Great starting point! Here's what you need:\n\n**Step 1: Open Accounts**\n- Demat + Trading Account (Zerodha, Groww, or Upstox)\n- Takes 1-2 days with Aadhaar\n\n**Step 2: Understand Basics**\n- Stocks = Ownership in a company\n- When company profits, stock price rises\n- Long-term (5+ years) = Less risky\n\n**With ₹10,000, Two Options:**\n\n**Option A: Index Funds (Recommended for beginners)**\n- Nifty 50 Index Fund\n- Diversified, less risky\n- SIP of ₹2,500/month\n\n**Option B: Blue-chip Stocks**\n- Buy 1-2 shares of stable companies\n- Examples: Reliance, TCS, HDFC Bank\n\n⚠️ Never invest money you can't afford to lose!\n\nWhich approach interests you?",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-9stu9s99-9ss9-9999-999s-9999ss999999",
          prompt_tokens: 178,
          completion_tokens: 134,
          total_tokens: 312,
          finish_reason: "stop",
          latency_ms: 312,
        },
        createdAt: "2024-01-22T10:00:03Z",
      },
      {
        role: "user",
        text: "What is SIP? And difference between stocks and mutual funds?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-22T10:01:00Z",
      },
      {
        role: "assistant",
        text: "**SIP (Systematic Investment Plan):**\nInvesting a fixed amount regularly (monthly), regardless of market conditions.\n\n*Example:* ₹2,500 every month automatically buys units\n- Market down = You buy more units\n- Market up = Your existing units grow\n\n**Stocks vs Mutual Funds:**\n\n| Aspect | Stocks | Mutual Funds |\n|--------|--------|-------------|\n| What | Single company | Basket of stocks |\n| Risk | High | Lower (diversified) |\n| Research | You do it | Fund manager does it |\n| Minimum | ₹1 (fractional) | ₹500 |\n| Control | Full | None |\n\n**Analogy:**\n- Stocks = Buying one fruit\n- Mutual Fund = Buying a fruit basket\n\nFor beginners, mutual funds via SIP is safer. You can learn stocks gradually.",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-0tuv0t00-0tt0-0000-000t-0000tt000000",
          prompt_tokens: 167,
          completion_tokens: 89,
          total_tokens: 256,
          finish_reason: "stop",
          latency_ms: 267,
        },
        createdAt: "2024-01-22T10:01:03Z",
      },
      {
        role: "user",
        text: "How do I research which stock to buy?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-22T10:02:00Z",
      },
      {
        role: "assistant",
        text: "Here's a beginner-friendly framework:\n\n**1. Fundamental Analysis (Long-term)**\n- P/E Ratio: Below 25 is generally good\n- Revenue growth: Should increase yearly\n- Debt: Lower is better\n- Promoter holding: Above 50% is good\n\n**2. Check These Free Tools:**\n- Screener.in - Financial data\n- Tickertape - Stock analysis\n- Moneycontrol - News & data\n\n**3. Simple Rules for Beginners:**\n- Invest in companies whose products you use\n- Profitable for at least 5 years\n- Leader in their industry\n- Avoid penny stocks (below ₹50)\n\n**My Suggestion:**\nStart with Nifty 50 companies. They're already filtered for quality.\n\n**Learn More:** Read \"The Intelligent Investor\" or watch CA Rachana Ranade on YouTube.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-1uvw1u11-1uu1-1111-111u-1111uu111111",
          prompt_tokens: 167,
          completion_tokens: 55,
          total_tokens: 222,
          finish_reason: "stop",
          latency_ms: 234,
        },
        createdAt: "2024-01-22T10:02:02Z",
      },
    ],
    createdAt: "2024-01-22T10:00:00Z",
    updatedAt: "2024-01-22T10:02:02Z",
  },

  // Conversation 9: History Question
  {
    
    user: "696dd8cf06227e5f6a09c04e",
    title: "Indian Independence Movement",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 498,
      completion_tokens: 234,
      total_tokens: 732,
    },
    messages: [
      {
        role: "user",
        text: "Explain the Quit India Movement briefly",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-23T15:00:00Z",
      },
      {
        role: "assistant",
        text: "**Quit India Movement (1942)**\n\n**What:** A mass civil disobedience movement demanding an end to British rule.\n\n**When:** Launched on August 8, 1942\n\n**Leader:** Mahatma Gandhi\n\n**Famous Slogan:** \"Do or Die\" (करो या मरो)\n\n**Why it happened:**\n- Britain was weakened by World War II\n- Failure of Cripps Mission\n- Gandhi wanted complete independence, not promises\n\n**Key Events:**\n- Entire Congress leadership arrested within hours\n- Leaderless masses continued protests\n- Over 100,000 people arrested\n- Movement suppressed but British realized they couldn't hold India\n\n**Impact:** Demonstrated India's resolve. Britain decided to leave after WWII ended.",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-2vwx2v22-2vv2-2222-222v-2222vv222222",
          prompt_tokens: 156,
          completion_tokens: 89,
          total_tokens: 245,
          finish_reason: "stop",
          latency_ms: 256,
        },
        createdAt: "2024-01-23T15:00:02Z",
      },
      {
        role: "user",
        text: "What was the Cripps Mission?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-23T15:01:00Z",
      },
      {
        role: "assistant",
        text: '**Cripps Mission (March 1942)**\n\n**What:** A British proposal sent to negotiate with Indian leaders during WWII.\n\n**Led By:** Sir Stafford Cripps (British Cabinet Minister)\n\n**Britain\'s Offer:**\n- Dominion status after the war (not full independence)\n- Indians could frame their own constitution\n- Provinces could opt out of the Union\n\n**Why It Failed:**\n\n| Rejected By | Reason |\n|-------------|--------|\n| Congress | Wanted immediate independence, not vague promises |\n| Muslim League | Didn\'t guarantee Pakistan |\n| Gandhi | Called it "a post-dated cheque on a crashing bank" |\n\n**Result:** Mission failed, leading directly to the Quit India Movement 5 months later.\n\n**Famous Quote:** Gandhi\'s "post-dated cheque" remark summarized Indian frustration perfectly.',
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-3wxy3w33-3ww3-3333-333w-3333ww333333",
          prompt_tokens: 178,
          completion_tokens: 78,
          total_tokens: 256,
          finish_reason: "stop",
          latency_ms: 234,
        },
        createdAt: "2024-01-23T15:01:02Z",
      },
      {
        role: "user",
        text: "Who were the main leaders besides Gandhi?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-23T15:02:00Z",
      },
      {
        role: "assistant",
        text: 'Here are the key leaders of the independence movement:\n\n**Congress Leaders:**\n1. **Jawaharlal Nehru** - First PM, Gandhi\'s political heir\n2. **Sardar Vallabhbhai Patel** - "Iron Man," united princely states\n3. **Subhas Chandra Bose** - INA founder, "Jai Hind"\n4. **Maulana Azad** - Muslim leader in Congress\n5. **Rajendra Prasad** - First President of India\n\n**Revolutionary Path:**\n6. **Bhagat Singh** - Legendary martyr\n7. **Chandrashekhar Azad** - Never caught alive\n8. **Lala Lajpat Rai** - "Punjab Kesari"\n\n**Women Leaders:**\n9. **Sarojini Naidu** - "Nightingale of India"\n10. **Kasturba Gandhi** - Died during Quit India imprisonment\n\nEach had different ideologies but the same goal: freedom.',
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-4xyz4x44-4xx4-4444-444x-4444xx444444",
          prompt_tokens: 164,
          completion_tokens: 67,
          total_tokens: 231,
          finish_reason: "stop",
          latency_ms: 223,
        },
        createdAt: "2024-01-23T15:02:02Z",
      },
    ],
    createdAt: "2024-01-23T15:00:00Z",
    updatedAt: "2024-01-23T15:02:02Z",
  },

  // Conversation 10: Science Explanation
  {
    
    user: "696dd8cf06227e5f6a09c04e",
    title: "Black Holes Explained",
    isPinned: false,
    activeModel: "llama-3.1-8b-instant",
    totalUsage: {
      prompt_tokens: 478,
      completion_tokens: 256,
      total_tokens: 734,
    },
    messages: [
      {
        role: "user",
        text: "Explain black holes in simple terms",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-24T21:00:00Z",
      },
      {
        role: "assistant",
        text: '**Black Hole = A region where gravity is so strong that nothing can escape, not even light.**\n\n**How They Form:**\nWhen a massive star (10+ times our Sun) dies, it collapses on itself. All that mass crushes into an incredibly tiny point.\n\n**Simple Analogy:**\nImagine compressing Earth into the size of a marble. That\'s how dense black holes are!\n\n**Key Parts:**\n1. **Singularity** - The infinitely dense center point\n2. **Event Horizon** - The "point of no return" boundary\n\n**Fun Facts:**\n- If you fell in, you\'d be stretched like spaghetti ("spaghettification")\n- Time slows down near a black hole\n- They don\'t "suck" things in - they\'re just very heavy\n\nWant me to explain what happens if you fall into one?',
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-5yza5y55-5yy5-5555-555y-5555yy555555",
          prompt_tokens: 145,
          completion_tokens: 112,
          total_tokens: 257,
          finish_reason: "stop",
          latency_ms: 289,
        },
        createdAt: "2024-01-24T21:00:02Z",
      },
      {
        role: "user",
        text: "Yes! What would happen if I fell into a black hole?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-24T21:01:00Z",
      },
      {
        role: "assistant",
        text: "This is where physics gets wild!\n\n**Your Experience (Inside):**\n1. You cross the event horizon - visually, nothing special\n2. Gravity pulls your feet stronger than your head\n3. Your body stretches vertically, compresses horizontally\n4. This is called **spaghettification** (seriously!)\n5. Eventually, you become a stream of atoms\n\n**What Others See (Outside):**\n- You appear to slow down at the event horizon\n- Your image freezes and fades to red\n- You seem to never actually cross it\n- Light from you gets increasingly redshifted\n\n**Time Dilation:**\n- If you somehow survived near the edge\n- 1 hour for you = years for people on Earth\n- (Like in the movie Interstellar!)\n\n**Reality:** You'd die before experiencing any of this - radiation near black holes is lethal.",
        favorite: true,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-6zab6z66-6zz6-6666-666z-6666zz666666",
          prompt_tokens: 167,
          completion_tokens: 89,
          total_tokens: 256,
          finish_reason: "stop",
          latency_ms: 267,
        },
        createdAt: "2024-01-24T21:01:02Z",
      },
      {
        role: "user",
        text: "Is there a black hole near Earth?",
        favorite: false,
        metadata: null,
        createdAt: "2024-01-24T21:02:00Z",
      },
      {
        role: "assistant",
        text: "Don't worry, we're safe!\n\n**Nearest Known Black Hole:**\n**Gaia BH1** - About 1,560 light-years away\n- Discovered in 2022\n- ~10 times the mass of our Sun\n- Completely harmless at this distance\n\n**For Comparison:**\n- 1 light-year = 9.46 trillion kilometers\n- The Moon is just 1.3 light-seconds away\n- We're incredibly far from any black hole\n\n**Could a Black Hole Come to Earth?**\nExtremely unlikely because:\n- They don't \"wander around\" randomly\n- Space is mostly empty\n- Even if one approached, we'd have millions of years warning\n\n**Supermassive One:**\n- **Sagittarius A*** sits at our galaxy's center\n- 26,000 light-years away\n- 4 million times the Sun's mass\n- We orbit around it safely!\n\n**Bottom Line:** You're more likely to win the lottery 1000 times than be affected by a black hole!",
        favorite: false,
        metadata: {
          model: "llama-3.1-8b-instant",
          request_id: "chatcmpl-7abc7a77-7aa7-7777-777a-7777aa777777",
          prompt_tokens: 166,
          completion_tokens: 55,
          total_tokens: 221,
          finish_reason: "stop",
          latency_ms: 223,
        },
        createdAt: "2024-01-24T21:02:02Z",
      },
    ],
    createdAt: "2024-01-24T21:00:00Z",
    updatedAt: "2024-01-24T21:02:02Z",
  },
];

import Conversation from "../../../server/src/models/conversation.js";


async function inserIntoConversation() {
  await Conversation.insertMany(dummyConversations);

  console.log("done inserting conversations");
}

export { inserIntoConversation };
